<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cb|cbs</string>
	</array>
	<key>name</key>
	<string>Cuby</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#class_definitions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#method_definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parameters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single_line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_method_calls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#global_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#instance_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cuby_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double_quoted_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_methods</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignment_operators</key>
		<dict>
			<key>comment</key>
			<string>Assignment operators</string>
			<key>match</key>
			<string>\*\*=|[+\/\-=\*%]?=</string>
			<key>name</key>
			<string>keyword.operator.assignment.cuby</string>
		</dict>
		<key>boolean_operators</key>
		<dict>
			<key>comment</key>
			<string>Boolean Operators</string>
			<key>match</key>
			<string>[&lt;&gt;]=|[&lt;&gt;]|\bor\b|\band\b|\bnot\b|\bisnt\b|\bis\b</string>
			<key>name</key>
			<string>keyword.operator.boolean.cuby</string>
		</dict>
		<key>class_definitions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.keyword.class.cuby</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.cuby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class definitions</string>
			<key>match</key>
			<string>(class)\s+([A-Z][a-zA-Z_\-]+[a-zA-Z_])</string>
		</dict>
		<key>class_method_calls</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.cuby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method calls</string>
			<key>match</key>
			<string>([A-Z][a-zA-Z0-9_\-]+[A-Za-z0-9_])\.</string>
		</dict>
		<key>class_variable</key>
		<dict>
			<key>comment</key>
			<string>Class variables start with @@</string>
			<key>match</key>
			<string>@@[a-zA-Z_][a-zA-Z0-9_\-]+[a-zA-Z0-9_]\b</string>
			<key>name</key>
			<string>variable.other.class.cuby</string>
		</dict>
		<key>constant_variable</key>
		<dict>
			<key>comment</key>
			<string>Constant</string>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z0-9_\-]+[a-zA-Z0-9_])\b</string>
			<key>name</key>
			<string>variable.other.constant.cuby</string>
		</dict>
		<key>cuby_keywords</key>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(?:\b(do|end|class|load|if|while|namespace|else|elsif|return|break|next|true|yes|on|false|no|off|nil|self|property)\b)|(\bdefined\?)</string>
			<key>name</key>
			<string>constant.keyword.cuby</string>
		</dict>
		<key>double_quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cuby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double quoted string</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cuby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cuby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Escaped character</string>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.cuby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_cuby</string>
				</dict>
			</array>
		</dict>
		<key>general_operators</key>
		<dict>
			<key>comment</key>
			<string>General operators</string>
			<key>match</key>
			<string>::|:|\(|\)|\[|\]|\?|,</string>
			<key>name</key>
			<string>keyword.operator.general.cuby</string>
		</dict>
		<key>global_variable</key>
		<dict>
			<key>comment</key>
			<string>Global Variables</string>
			<key>match</key>
			<string>\$[a-zA-Z_][a-zA-Z0-9_\-]+[a-zA-Z0-9_]\b</string>
			<key>name</key>
			<string>variable.other.global.cuby</string>
		</dict>
		<key>instance_variable</key>
		<dict>
			<key>comment</key>
			<string>Instance variable</string>
			<key>match</key>
			<string>@[a-zA-Z_][a-zA-Z0-9_\-]+[a-zA-Z0-9_]\b</string>
			<key>name</key>
			<string>variable.other.instance.cuby</string>
		</dict>
		<key>interpolated_cuby</key>
		<dict>
			<key>begin</key>
			<string>\#\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.cuby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Interpolated Cuby variables</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>source.cuby.embedded.cuby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#global_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instance_variable</string>
				</dict>
			</array>
		</dict>
		<key>math_operators</key>
		<dict>
			<key>comment</key>
			<string>Math operators</string>
			<key>match</key>
			<string>\*\*|[\*\-+\/%]</string>
			<key>name</key>
			<string>keyword.operator.math.cuby</string>
		</dict>
		<key>method_definition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cuby</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.keyword.function.start.cuby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method name</string>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z0-9_\-]+[a-zA-Z0-9_])\s+(do)</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>comment</key>
			<string>Integer and Float</string>
			<key>match</key>
			<string>(?:(?:0|[\d_]+)\.[\d_]+)|(?:[\d_]+)</string>
			<key>name</key>
			<string>constant.numeric.cuby</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#boolean_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general_operators</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parameter.begin.cuby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parameter.end.cuby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>function.parameter.list.cuby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instance_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general_operators</string>
				</dict>
			</array>
		</dict>
		<key>single_line_comment</key>
		<dict>
			<key>comment</key>
			<string>Single line comment</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.cuby</string>
		</dict>
		<key>special_methods</key>
		<dict>
			<key>comment</key>
			<string>Special methods, like 'new'</string>
			<key>match</key>
			<string>new</string>
			<key>name</key>
			<string>keyword.other.special-method.cuby</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cuby</string>
	<key>uuid</key>
	<string>b14a47ec-d7dd-44c7-9d8f-ee97fbd52e85</string>
</dict>
</plist>
